完成用例整理
ArielHeleneto/RISCV-testcase pull request #17
Opened 2022-11-25 08:12 UTC by GICEGreenIce

2022-11-25 08:32 UTC, ArielHeleneto requested changes
有些小细节。

2022-11-25 08:32 UTC, ArielHeleneto commented on Thunderbird/testcase/创建和使用邮件列表.md
> +### 创建邮件列表
这里加个空行。

2022-11-25 08:32 UTC, ArielHeleneto commented on Thunderbird/testcase/创建和使用邮件列表.md
> +在邮件工具栏，找到 **通讯录**。
加空行。

2022-11-25 08:32 UTC, ArielHeleneto commented on Thunderbird/testcase/创建和使用邮件列表.md
> +* 这会打开一个新的消息窗口，左侧是 '联系人侧栏'。
这里缩进两个空格，无序列表用-

2022-11-25 08:32 UTC, ArielHeleneto commented on Thunderbird/testcase/消息列表栏.md
> +本文中，**预期结果**中不含有图片，但不影响测试者理解预期结果。
这不是有图吗？？？

2022-11-25 08:32 UTC, ArielHeleneto commented on Thunderbird/testcase/自定义起始页.md
> +1. 点击 Thunderbird 窗口顶部的 `编辑` 菜单，选择 `首选项`，或点击 `菜单` 按钮后选择 `首选项`。
空行

2022-11-26 07:28 UTC, GICEGreenIce commented on Thunderbird/testcase/创建和使用邮件列表.md
> +在邮件工具栏，找到 **通讯录**。
已修改

2022-11-26 07:28 UTC, GICEGreenIce commented on Thunderbird/testcase/创建和使用邮件列表.md
> +* 这会打开一个新的消息窗口，左侧是 '联系人侧栏'。
已修改

2022-11-26 07:29 UTC, GICEGreenIce commented on Thunderbird/testcase/消息列表栏.md
> +本文中，**预期结果**中不含有图片，但不影响测试者理解预期结果。
已修改

2022-11-26 07:31 UTC, GICEGreenIce commented on Thunderbird/testcase/自定义起始页.md
> +1. 点击 Thunderbird 窗口顶部的 `编辑` 菜单，选择 `首选项`，或点击 `菜单` 按钮后选择 `首选项`。
已修改

2022-11-26 08:03 UTC, closed without merging